[project]
name = "file-share-bot"
version = "0.1.0"
description = "A Telegram bot to share files via deep links"
authors = ["Your Name <you@example.com>"]
requires-python = ">=3.11"
dependencies = [
    "python-telegram-bot>=22.3"
] 